### ISSUE TITLE
Release v0.1.0

### ISSUE THREAD

**Issue by adityasaky** [gittuf/gittuf#55]
This issue is a tracker of things we need to implement before we can tag v0.1.0.
- [x] Support verifying RSL states (#62)
- [x] Support file policies (#82)
- [x] Add syncing functionality to push/pull refs/gittuf/* between remotes (#56)
- [x] `verify-commit` and `verify-tag` functionality (#15)

**Comment by adityasaky** [comment]
https://github.com/gittuf/gittuf/releases/tag/v0.1.0
